spring.application.name=envio_servicio_servicioso
server.port=8102

spring.datasource.url=jdbc:mysql://localhost:3306/dbenvio
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URLs de otros servicios
pago.service.url=http://localhost:9095
pedido.service.url=http://localhost:8104