spring.application.name=compra_servicio
server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/dbcompra
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

producto.service.url=http://localhost:9094
cupon.service.url=http://localhost:9093
pago.service.url=http://localhost:9095